name: Build Operator Image

on:
  workflow_dispatch:

jobs:
  build-pr-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Log current commit
        run: echo "Building image from commit ${{ github.event.pull_request.head.sha }}"

      - name: Install podman
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman

      - name: Login to quay.io
        shell: bash
        env:
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        run: |
          podman login quay.io -u ${QUAY_USERNAME} -p ${QUAY_TOKEN}

      - name: Build and push PR image
        run: |
          make docker-build docker-push -e IMG=quay.io/opendatahub/llama-stack-k8s-operator:pr-${{ github.event.number }}
