name: PR E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create kind config
        run: |
          cat > kind-config.yaml << EOF
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          containerdConfigPatches:
          - |-
            [plugins."io.containerd.grpc.v1.cri".registry]
              config_path = "/etc/containerd/certs.d"
          nodes:
          - role: control-plane
            kubeadmConfigPatches:
            - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  system-reserved: memory=500Mi
                  eviction-hard: memory.available<200Mi
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          EOF

      - name: Create k8s Kind Cluster
        id: kind
        uses: helm/kind-action@v1
        with:
          registry: true
          registry_name: kind-registry
          registry_port: 5000
          registry_enable_delete: true
          config: kind-config.yaml

      - name: Build operator image
        run: |
          docker build -t localhost:5000/llama-stack-k8s-operator:pr-${{ github.event.pull_request.number }} -f Dockerfile .
          docker tag localhost:5000/llama-stack-k8s-operator:pr-${{ github.event.pull_request.number }} localhost:5000/llama-stack-k8s-operator:latest

      - name: Push operator image to local registry
        run: |
          docker push localhost:5000/llama-stack-k8s-operator:pr-${{ github.event.pull_request.number }}

          # Deploy the operator
          make deploy IMG=localhost:5000/llama-stack-k8s-operator:pr-${{ github.event.pull_request.number }}
          
          # Wait for operator deployment to be ready
          if ! kubectl wait --for=condition=available --timeout=300s deployment/llama-stack-k8s-operator-controller-manager -n llama-stack-k8s-operator-system; then
            echo "Deployment failed to become ready. Debugging information:"
            echo "=== Deployment Status ==="
            kubectl describe deployment llama-stack-k8s-operator-controller-manager -n llama-stack-k8s-operator-system
            echo "=== Pod Status ==="
            kubectl get pods -n llama-stack-k8s-operator-system
            echo "=== Pod Logs ==="
            kubectl logs -n llama-stack-k8s-operator-system -l app.kubernetes.io/name=llama-stack-k8s-operator --tail=100
            echo "=== Events ==="
            kubectl get events -n llama-stack-k8s-operator-system --sort-by='.lastTimestamp'
            exit 1
          fi

      - name: Run e2e tests
        run: |
          make e2e-tests 
